## LAB - Modyfikacja serii danych
1. Zaimportuj moduł pandas i nadaj mu standardowy alias. Do zmiennej fuel wczytaj zawartość pliku fuel.csv. Podczas wczytywania skorzystaj dodatkowego argumentu low_memory=False. Wyświetl nagłówek tak utworzonego Data Frame.
2. Jeśli chcesz w Jupyter Notebook zobaczyć więcej nazw kolumn zamiast kropeczek należy zmienić opcję max_columns. Wykonaj polecenie:
    #### pd.options.display.max_columns=500
3. Wyświetl 10 pierwszych pozycji i zwróć uwagę na to ile kolumn posiada ten plik
4. Wyświetl 5 ostatnich wierszy
5. Wczytaj do zmiennej fuel ponownie zawartość pliku fuel.csv, ale tym razem pobierz tylko następujące kolumny: 'Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'
6. Wyświetl nagłówek data frame fuel. Zauważ jak jest zbudowany indeks
7. Wczytaj do zmiennej fuel ponownie zawartość pliku fuel.csv, ale tym razem pobierz tylko następujące kolumny: 'Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'. Jako indeks wybierz 'Vehicle ID'
8. Wyświetl nagłówek data frame fuel. Zauważ jak jest zbudowany indeks

In [2]:
import pandas as pd

In [7]:
fuel = pd.read_csv('../zasoby/fuel.csv', low_memory=False)
pd.options.display.max_columns=25
fuel.head()

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,Engine Cylinders,Engine Displacement,...,Hours to Charge (120V),Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001.0,(FFS),6.0,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005.0,(FFS) CA model,6.0,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002.0,(FFS),4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006.0,(FFS) CA model,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830.0,(FFS),4.0,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0

In [8]:
fuel.tail(10)

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,Engine Cylinders,Engine Displacement,...,Hours to Charge (120V),Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
31674,31673,2012,Mitsubishi,i-MiEV,Subcompact Cars,Rear-Wheel Drive,Automatic (A1),NaN,141.0,NaN,NaN,NaN,...,0.0,7.0,0.0,0.0,0.0,0.0,62.0,68.5545,54.8184,NaN,0.0,0.0
31675,32062,2012,Mitsubishi,Lancer,Compact Cars,All-Wheel Drive,Auto(AM6),NaN,115.0,NaN,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31676,32059,2012,Mitsubishi,Lancer,Compact Cars,Front-Wheel Drive,Auto(AV-S6),NaN,112.0,NaN,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31677,32061,2012,Mitsubishi,Lancer,Compact Cars,Front-Wheel Drive,Auto(AV-S6),NaN,114.0,NaN,4.0,2.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31678,32058,2012,Mitsubishi,Lancer,Compact Cars,Front-Wheel Drive,Manual 5-Speed,NaN,111.0,NaN,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31679,32060,2012,Mitsubishi,Lancer,Compact Cars,Front-Wheel Drive,Manual 5-Speed,NaN,113.0,NaN,4.0,2.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31680,32063,2012,Mitsubishi,Lancer AWD,Compact Cars,All-Wheel Drive,Auto(AV-S6),NaN,116.0,NaN,4.0,2.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31681,32065,2012,Mitsubishi,Lancer Evolution,Compact Cars,All-Wheel Drive,Auto(AM6),NaN,132.0,NaN,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31682,32064,2012,Mitsubishi,Lancer Evolution,Compact Cars,All-Wheel Drive,Manual 5-Speed,NaN,131.0,NaN,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,NaN,0.0,0.0
31683,32106,2012,Mitsubish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
fuel = pd.read_csv('../zasoby/fuel.csv', usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'])

In [11]:
fuel.head()

,Vehicle ID,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0

In [13]:
fuel = pd.read_csv('../zasoby/fuel.csv', usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], index_col='Vehicle ID')

In [15]:
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0